# Site settings
title: GGJ 2024 - HVL Campus Førde
email: robotikklabben.forde@gmail.com
url: https://hvlforde.github.io/globalgamejam_hvl/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
short_about: "HVL Campus Førde is hosting a local event for Global Game Jam 2024"
meta_author: LastName FirstName
baseurl: "/globalgamejam_hvl"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFFFFF   # 89CFF0 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 0e3c7b #FD6E8A
  secondary-dark: 0e3c7b  #233140 #A2122F

# Footer settings
footer:
  copyright: HVL Førde
  location: Location
#  social: Around the Web
#  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Svanehaugveien 1
  - line: 6812 Førde, Norway

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""


include:
  - _pages